# Generated by Django 3.2.6 on 2023-12-10 17:54

import apps.home.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('resume', models.FileField(blank=True, null=True, upload_to=apps.home.models.upload_resume, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc'])])),
                ('internship_certificate', models.FileField(blank=True, null=True, upload_to=apps.home.models.upload_internship_certificate, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc'])])),
                ('courses_completed', models.FileField(blank=True, null=True, upload_to=apps.home.models.upload_courses_completed, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc'])])),
                ('other_certificate', models.FileField(blank=True, null=True, upload_to=apps.home.models.upload_other_certificate, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc'])])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
    ]
