# Generated by Django 3.2.6 on 2023-12-11 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='media',
            options={'ordering': ('id',)},
        ),
    ]
