# Generated by Django 3.2.6 on 2023-12-11 12:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0002_alter_media_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='shared_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shared_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
